### ISSUE TITLE
Don't Blindly Try to Construct Schemas

### ISSUE THREAD

**Issue by hjc** [fuhrysteve/marshmallow-jsonschema#18]
So, if you have a `Nested` field that you pass a schema you've already constructed, marshmallow-jsonschema fails with the following error:

```
  File "~/.env/local/lib/python2.7/site-packages/marshmallow_jsonschema/base.py", line 147, in _from_nested_schema
    schema = cls().dump(field.nested()).data
TypeError: 'LastAttachmentSchema' object is not callable
```

This is what the code for that Nested field looks like:

``` py
class ThreadPaginatedSchema(ThreadSchema):
    """Schema for paginated threads"""
    last_attachments = fields.Nested(
        LastAttachmentSchema(context={'child': True}), many=True
    )   

    class Meta(object):
        """Keys to remove"""
        exclude = ('project_id',)
```

We need to construct the schema so we can update it's context and **JUST** it's context (because setting a context of `child=True` on the parent won't work). Looking at Marshmallow's `Nested` field, they do handle this usecase. Should be as simple as adding an `isinstance` check around the line that errors.

**Comment by hjc1710** [comment]
Oh, the quick fix I used to get around this is:

```
class LastAttachmentSchema(BaseSchema):
    """Schema for the Materials in the last Message in a thread"""
    # ... fields
    def __call__(self):
        return self
```

Just making it callable.
