### ISSUE TITLE
schema produced for an integer field breaks react-jsonschema-form

### ISSUE THREAD

**Issue by rsyring** [fuhrysteve/marshmallow-jsonschema#40]
I've created a marshmallow schema with an integer field.  This library generates JSON schema for the field as:

```
    "id": {
      "format": "integer",
      "title": "id",
      "type": "number"
    },
```

When I feed that schema to the `Form` React component from https://github.com/mozilla-services/react-jsonschema-form, I get an error:

> Error: No widget "integer" for type "number"

Based on their examples and my limited reading of the JSON Schema spec, maybe the correct JSON schema should be:

```
    "id": {
      "title": "id",
      "type": "integer"
    },
```

**Comment by bartfeenstra** [comment]
JSON Schema [v4](https://github.com/json-schema-org/json-schema-spec/blob/master/archive/draft-04/schema.json) and [v6](https://json-schema.org/schema) both allow both `integer` and `number`, so the schema output is correct. If I read https://github.com/mozilla-services/react-jsonschema-form#for-number-and-integer-fields correctly, that means you used `integer` as the widget type, but you can only choose from the `updown`, `range, and `radio` widgets for either an `integer` or `number` field.

**Comment by fuhrysteve** [comment]
Sounds like this isn't an issue in marshmallow-jsonschema, so closing for now. Please reopen if anyone thinks there's something that needs to be addressed still!
