### ISSUE TITLE
0.5.0 release?

### ISSUE THREAD

**Issue by stringfellow** [fuhrysteve/marshmallow-jsonschema#42]
There's some stuff in master that's not on pypi - also PR #39 has a build fail which I think is just a travis blip - could it be re-built and merged if acceptable?

**Comment by stringfellow** [comment]
@fuhrysteve I would be very happy to share the load on making releases etc if you're willing to allow me write access (and perhaps lock down the merge on PRs so that they require approval)?

**Comment by fuhrysteve** [comment]
My apologies! I'll spend some time this weekend on maintenance

**Comment by fuhrysteve** [comment]
Sorry for the delay - 0.5.0 is out - let me know if you have any issues! Thanks for all the PRs @stringfellow

**Comment by stringfellow** [comment]
Thanks very much! I would be very grateful for any hints you might have for https://github.com/fuhrysteve/marshmallow-jsonschema/pull/43 -- I had a very cursive look but couldn't see how it fits in immediately..

**Comment by fuhrysteve** [comment]
Sure thing - I will look into it soon!
