### ISSUE TITLE
Marshmallow-mongoenine support

### ISSUE THREAD

**Issue by macfire** [fuhrysteve/marshmallow-jsonschema#53]
Are there any plans to support Marshmallow-Mongoengine ModelSchema feature, which will automatically create a base schema from a model?

I've been using the convenience of Marshmallow-Mongoengine to avoid having to recreate lengthy models into schemas (DRY), but would also to like to use marshmallow-jsonschema.  

The basic errors I've receive so far are `"unsupported field type <fields.ObjectId>"` and `"<fields.ReferenceField>"`.   All works fine if I manually create the schemas.

**Comment by fuhrysteve** [comment]
I'm not familiar with marshmallow-mongoengine (looks like it's moved to here: https://github.com/MongoEngine/marshmallow-mongoengine ), however if there's anything we can do here to improve support for it, I'd be glad to bring those changes in!
