### ISSUE TITLE
Shouldn't we treat marshmallow-jsonschema as a kind of marshmallow schema?

### ISSUE THREAD

**Issue by Hardtack** [fuhrysteve/marshmallow-jsonschema#7]
Marshmallow is a object serialization library. And also, marshmallow-jsonschema serializes(dumps) a form which.
So, in my opinion, marshmallow-jsonschema should be made as a kind of marshmallow schema. This schema will be schema of schema.

The API would be like this

    >>> json_schema = JSONSchema()
    >>> user_schema = UserSchema()
    >>> result = json_schema.dump(user_schema)
    >>> result.data
    {'properties': {'addresses': ...

**Comment by fuhrysteve** [comment]
This is a really clever and insightful design idea. I like this idea a lot better than what I was brainstorming about in #6

I wonder if we can actually make extend `marshmallow.Schema`, i.e. `class JSONSchema(Schema)`?

**Comment by Hardtack** [comment]
It seems to be able to do that. JSON schema generally has 4 fields `title`, `properties`, `required`, `type` all we have to do is making the as [method fields](https://marshmallow.readthedocs.org/en/latest/custom_fields.html#method-fields).

But there seem to exist a problem in handling `many` shema, and I suppose that we can handle them with [pre/post processing](https://marshmallow.readthedocs.org/en/latest/extending.html#pre-processing-and-post-processing-methods).

**Comment by Hardtack** [comment]
I'm making similar library with this concept. this one converts formencode's schema to json schema
https://gist.github.com/Hardtack/8baeba02bd509e489f38

**Comment by fuhrysteve** [comment]
I finally got around to throwing this together -- It's messy, but the tests pass!

**Comment by fuhrysteve** [comment]
Thanks again for your help @Hardtack !! check out the example I drew up that this sort of design allows for:

https://github.com/fuhrysteve/marshmallow-jsonschema#nested-example
