### ISSUE TITLE
Incompatible with marshmallow==3.0.0rc9

### ISSUE THREAD

**Issue by LukeMarlin** [fuhrysteve/marshmallow-jsonschema#84]
`marshmallow-jsonschema` works fine with `marshmallow<=3.0.0rc8`, however, due to the removal of [marshmallow.fields.LocalDateTime](url) as noted in [the changelog](https://github.com/marshmallow-code/marshmallow/blob/8cf1fb8d95f287d626ed0f38967c90198e28b476/CHANGELOG.rst#300rc9-2019-07-31), this line now fails:
https://github.com/fuhrysteve/marshmallow-jsonschema/blob/ee7fcaa543998b43452601767e3a6261ab84fe70/marshmallow_jsonschema/base.py#L99

As a side note, [Schema.dump() now returns data directly](https://github.com/marshmallow-code/marshmallow/blob/8cf1fb8d95f287d626ed0f38967c90198e28b476/CHANGELOG.rst#300rc9-2019-07-31), it's no longer a tuple, meaning that your examples won't work anymore after the next release

I'm not sure if it's ok for me to open the issue as this is a future release, but I wanted to let you know before it happens (and it seems it's going to be soon :+1: )

**Comment by fuhrysteve** [comment]
Thanks for the heads up! We're supporting both versions 2 & 3 for awhile (what does that remind you of?? :laughing:)

**Comment by fuhrysteve** [comment]
Thx for the pull!!

**Comment by LukeMarlin** [comment]
While #90 has been merged, it is not present in v0.7.0 which is in a newer commit.
Could you package the actual master version?

Also, would you consider doing the packaging automatically from master from now on? That would be better for your users as currently, we have no idea what's on pypi compared to the source

**Comment by LukeMarlin** [comment]
@fuhrysteve 
Just pinging, since I'm replying to a closed issue, I'm not sure you got the notification.

**Comment by fuhrysteve** [comment]
Hi @LukeMarlin ! thank you for keeping on top of it for me. I just pushed up the latest master as 0.8.0

Please let me know if you have any other issues!
