### ISSUE TITLE
Where is 0.7.0?

### ISSUE THREAD

**Issue by LukeMarlin** [fuhrysteve/marshmallow-jsonschema#91]
It is distributed in [pypi](https://pypi.org/project/marshmallow-jsonschema/#history), yet it's nowhere to be seen on [master](https://github.com/fuhrysteve/marshmallow-jsonschema/blob/master/setup.py).

There are a bunch of branches, none of them explicitly related to 0.7.0, so where does that pypi version come from?

**Comment by fuhrysteve** [comment]
Whoops! Had some uncommitted local changes. Thanks for pointing it out!!

https://github.com/fuhrysteve/marshmallow-jsonschema/commit/134433afc3806f2789952258ad4bbc1d2897fb7f
